---
galaxy_info:
  author: CISA ED-25-03 Maintainers
  description: Perform core dump preparation and trigger on ASA (DANGEROUS)
  license: Apache-2.0
  min_ansible_version: 2.14.0
dependencies: []
collections:
  - cisco.asa
  - ansible.netcommon
